### PR TITLE
WebAssembly -> IL Conversion

### PR DESCRIPTION
**Pull request by thegu5**
This is a rough draft for converting wasm to IL. I'm avoiding ISIL since it's abstracted around registers - and since wasm is stack based like IL, conversion is much easier without it. 

As of now, most instructions aren't implemented and the code is messy. I'll continually update this branch as I make progress.

This is very much an experiment, hopefully it gets somewhere

### CODE REVIEW

**Comment by SamboyCoding** [comment]
FWIW, my first two immediate thoughts:

1. ISIL is not "abstracted around registers". It supports stack based operations because x86 is primarily stack based.
2. I will not ever merge any solution for IL conversion into the main repository that uses a different system to everything else. You're fine to maintain this on your own but this PR will not be merged if it does not use ISIL.

**Comment by thegu5** [comment]
That makes sense - I'm closing this pr and moving it to a plugin with an output format. I really want to work on something that can be upstreamed and work well with existing systems, but I don't get how to go about doing stack based operations w/ ISIL. Maybe I need to research x86 more to learn how ISIL works...

**Comment by SamboyCoding** [comment]
It's literally just `InstructionSetIndependentOperand.MakeStack(stackOffset)` and then pass that as the operands to every instruction you define using the builder.

**Comment by thegu5** [comment]
🤦🏻 that took me way too long

**Pull request closed without merging**
