### PR TITLE
trimming flags conditioned on net6.0 or better

### PR DESCRIPTION
**Pull request by mitchcapper**
fix build failures when it tries to build with .net framework compat.

### CODE REVIEW

**Comment by SamboyCoding** [comment]
Not sure why this is necessary when you can just build with modern msbuild and `/p:TargetFramework=net472` [like the CI does](https://github.com/SamboyCoding/Cpp2IL/blob/new-analysis/.github/workflows/dotnet-core.yml#L32)

**Comment by mitchcapper** [comment]
I don't know, actually it was the CI that was failing,  https://github.com/mitchcapper/Cpp2IL/actions/runs/7225981068  my GH just isn't as good as your GH:)  I am guessing some environment variable but I saw the errors and figured conditioning it was the easiest fix.

**Comment by SamboyCoding** [comment]
Interesting ok, that looks like it might have been a breaking change in net8's msbuild.

**Comment by mitchcapper** [comment]
I have noticed .net8 is much more strict on things that previously worked

**Pull request merged**
