### PR TITLE
Core: Add InputModels, adapt CLI & GUI

### PR DESCRIPTION
**Pull request by Alluseri**
Now both CLI and GUI work off the same gamefile "parsers". This probably needs lots of fixes. Check TODOs.

### CODE REVIEW

**Comment by Alluseri** [comment]
Note: The compile errors when compiling for net472 weren't caused by me.

**Comment by SamboyCoding** [comment]
The compiler errors must have been caused by you, because development compiles fine for net472 right now. It looks like you removed the `using LibCpp2IL` at the top of the Program file, this is what caused it.

**Comment by Alluseri** [comment]
> The compiler errors must have been caused by you, because development compiles fine for net472 right now. It looks like you removed the `using LibCpp2IL` at the top of the Program file, this is what caused it.

Well that was dumb of me. OmniSharp probably marked it as unused and it got removed. I'll probably have to disable some relevant functions in VSCodium later

**Comment by Alluseri** [comment]
I'll write a better rewrite later

**Comment by Alluseri** [comment]
added fix, if it doesn't work I will cry

**Comment by Alluseri** [comment]
it works

**Pull request closed without merging**
